### ISSUE TITLE
Consider exporting `new_bare_iv` for dev use

### ISSUE THREAD

**Issue by TimTaylor** [DavisVaughan/ivs#30]
It would be useful to be able to utilise `new_bare_iv` when creating a `iv_proxy` method. Would you consider exporting with a "developer" usage documentation. I know I could duplicate the function but would prefer to rely on an exported api if possible.

**Comment by DavisVaughan** [comment]
I don't think the difference between that and `new_iv()` is worth it for extension developers

``` r
new_iv <- ivs::new_iv
new_bare_iv <- ivs:::new_bare_iv

bench::mark(new_iv(1L, 2L), new_bare_iv(1L, 2L), iterations = 1000000)
#> # A tibble: 2 × 6
#>   expression               min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>          <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 new_iv(1L, 2L)        1.68µs   2.01µs   475459.    3.07KB     25.2
#> 2 new_bare_iv(1L, 2L)    809ns   1.01µs   927760.        0B     25.1
```

<sup>Created on 2022-09-21 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment]
See also https://github.com/TimTaylor/ageivs/issues/2
