### ISSUE TITLE
 dbplyr support

### ISSUE THREAD

**Issue by kieran-mace** [DavisVaughan/ivs#58]
`ivs` is one of the most exciting packages I've seen in a long time! I'm wondering if you're planning on supporting dbplyr backend at all? given that you use `vctrs` I'm curious how much additional lift would be required to support that use case? 

I'd happily help out if you can provide guidance?

**Comment by DavisVaughan** [comment]
AFAICT there is nothing like this on the SQL side so I think a translation would be pretty difficult
